apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: NaN-pipeline-run-init
  namespace: my-go-app
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  labels:
    tekton.dev/pipeline: demo-dh-pipeline
    type: pipeline
spec:
  params:
    - name: source-repo
      value: 'https://github.com/cooktheryan/demo-dh.git'
    - name: source-branch
      value: main
    - name: output-image
      value: image-registry.openshift-image-registry.svc:5000//demo-dh
  pipelineRef:
    name: demo-dh-pipeline
  serviceAccountName: pipeline
  workspaces:
    - name: source-folder
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
